### ISSUE TITLE
Undefined behaviour in write_mailbox?

### ISSUE THREAD

**Issue by luctius** [stm32-rs/fdcan#30]
I **think** the following is undefined behaviour, since we should call 'as_mut_ptr', instead of 'as_ptr' (and lbuffer should be mut)?

https://github.com/stm32-rs/fdcan/blob/1045c9cecbe0d31c95f1af6bfaa6744b11c72091/src/lib.rs#L1333-L1342

**Comment by richardeoin** [comment]
I agree this is undefined behaviour, since data reached though an immutable reference is mutated. Also agreed with the proposed fix
