### ISSUE TITLE
Transmit and receive should use byte array

### ISSUE THREAD

**Issue by yorickdewid** [stm32-rs/fdcan#9]
I think the `FdCan::transmit` and possibly the `FdCan::receive0` and `FdCan::receive1` should accept a byte array instead of a `u32` vector. I understand the use of `u32` for RAM alignment but I think this should be handled internally with an optional padding.

Public `FdCan` functions should not have to use lambda's if they are not necessary. This would make things more idiomatic Rust.

I can draft a PR.

**Comment by yorickdewid** [comment]
@richardeoin What do you think?

**Comment by luctius** [comment]
I'm all for it. I had my reasons for using u32, but you make a valid case for why it should have been a byte array.

**Comment by richardeoin** [comment]
Agreed, I think PRs on either topic would be very welcome!

**Comment by richardeoin** [comment]
Closed in #10
